[package]
name    = "sandstorm"
version = "0.1.0"
authors = ["Ryan Stutsman <stutsman@cs.utah.edu>"]

[dependencies]
bytes   = "0.4.7"
byteorder = "1"
hashbrown = "0.1.8"
libc = "0.2.43"
libloading = "0.3"
spin = "0.5.2"
util = {path = "../util"}
