[package]
name = "util"
version = "0.1.0"
authors = ["Ankit Bhardwaj <bhrdwj.ankit@gmail.com>"]

[dependencies]
bincode      = "1.0"
rustlearn    = "0.5.0"
lazy_static  = "1.3.0"
hashbrown    = "0.1.8"
